[package]
name = "metronom"
version = "0.1.0"
edition = "2021"

[dependencies]
# remove later
bon = "2.3.0"
prometheus = "0.13.3"

quote = "1"
syn = "2"
darling = "0.20"
proc-macro2 = "1.0.86"
heck = "0.5.0"

[lib]
proc-macro = true
